  check_for_known_vulnerabilities_in_third_party_libraries:
    comment: 'Checked'
  check_for_reverse_shells:
    comment: 'Checked'
  check_authorization_credentials:
    comment: 'Checked'
  check_embedded_links:
    comment: 'Checked'
  check_fs_writes:
    comment: 'Checked'
  check_search_acceleration:
    comment: 'Checked'
  check_dependencies:
    comment: 'Checked'
  check_documented_included_open_source:
    comment: 'Checked'
  check_editing_and_proofreading:
    comment: 'Checked'
  check_requires_access_to_files_outside_apps_dir:
    comment: 'Checked'
  check_link_includes_contact_info:
    comment: 'Checked'
  check_hard_coded_paths:
    comment: 'Checked'
  check_for_shell:
    comment: 'Checked'
