  check_app_icon_2x_dimensions:
    comment: 'ADDON-000: Expected Failure'
  check_app_icon_2x_is_png:
    comment: 'ADDON-000: Expected Failure'
  check_app_icon_dimensions:
    comment: 'ADDON-000: Expected Failure'
  check_app_icon_is_png:
    comment: 'ADDON-000: Expected Failure'
