  check_app_icon_2x_dimensions:
    comment: 'Expected Failure'
  check_app_icon_2x_is_png:
    comment: 'Expected Failure'
  check_app_icon_dimensions:
    comment: 'Expected Failure'
  check_app_icon_is_png:
    comment: 'Expected Failure'
