name: pre-commit

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
    - name: Install python
      run: apt-get update && apt-get install python3 python3-venv python3-pip -y
    - name: Checkout
      uses: actions/checkout@v4
    - name: pre-commit
      uses: pre-commit/action@v3.0.1
    - name: pre-commit-ci
      uses: pre-commit-ci/lite-action@v1.0.2
      if: always()
