name: pre-commit

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
    - name: Update Container
      run: apt-get update && apt-get upgrade -y
    - name: Install Dependencies
      run: apt-get update && apt-get install python3 python3-venv python3-pip git -y
    - name: Install pre-commit
      run: python3 -m pip install pre-commit
    - name: Checkout repo
      uses: actions/checkout@v4
      # with:
      #   path: repo
    # - name: Cache
    #   uses: actions/cache@v4
    #   with:
    #     path: ~/.cache/pre-commit
    #     key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Add safe.directory
      run: git config --global --add safe.directory $pwd
    # - name: Git status
    #   run: git status
    #   working-directory: repo
    # - name: Run pre-commit
    #   run: pre-commit run --show-diff-on-failure --color=always --all-files
    #   working-directory: repo
    - name: pre-commit-ci
      uses: pre-commit-ci/lite-action@v1.0.2
      if: always()
