name: pre-commit

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
    - name: Update container
      run: apt-get update && apt-get upgrade -y
    - name: Install python
      run: apt-get update && apt-get install python3 python3-venv python3-pip -y
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install pre-commit
      run: python3 -m pip install pre-commit
    # - name: pre-commit-ci
    #   uses: pre-commit-ci/lite-action@v1.0.2
    #   if: always()
