name: pre-commit

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
    - run: apt-get update && apt-get install python3 -y
    - uses: actions/checkout@v4
    - uses: pre-commit/action@v3.0.1
    - uses: pre-commit-ci/lite-action@v1.0.2
      if: always()
