name: splunk-app-inspect

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: splunk_app

      - name: List contents of app folder
        run: ls -la splunk_app

      - name: Package app folder
        run: tar --exclude='.git' --format ustar -cvzf splunk_app.tar.gz splunk_app

      - name: Inspect app
        uses: splunk/appinspect-cli-action@v2.5.0
        with:
          app_path: splunk_app.tar.gz
