name: splunk-app-inspect

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout app
        uses: actions/checkout@v4
        with:
          path: splunk_app

      - name: List contents of app
        run: ls -la splunk_app

      - name: Package app
        run: tar --exclude='.git' --exclude='.github' --exclude='.appinspect.expect.yaml' --exclude='indexes.conf' --format ustar -cvzf splunk_app.tar.gz splunk_app

      - name: Inspect app
        uses: splunk/appinspect-cli-action@v2.5.0
        with:
          app_path: splunk_app.tar.gz
          appinspect_expected_failures: splunk_app/.appinspect.expect.yaml
